# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Kingdom of Lydia
tagline:          'blog'
description:      'A technical blog by <a href="http://baixuanwang.com" target="_blank">Baixuan Wang</a>.'
url:              http://blog.baixuanwang.com
baseurl:          /

author:
  name:           'Baixuan Wang'
  url:            https://twitter.com/baixuanwang

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/beyondLydia/beyondLydia.github.io