# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Kingdom of Lydia 
tagline:          'A Jekyll theme'
description:      'A Game Developer and Technical Artist's blog. Visit my personal website at <a href="http://baixuanwang.com" target="_blank">Baixuan</a>
 Made by <a href="https://twitter.com/baixuanwang" target="_blank">@baixuanwang</a>.'
url:              http://baixuanwang.com
baseurl:          /

author:
  name:           'Baixuan Wang'
  url:            https://twitter.com/baixuanwang

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/beyondLydia/beyondLydia.github.io/
